version: '3'
services:
    game_api:
        build:
            context: .
        image: bensonarts/gameapi
        command: ["yarn", "serve"]
        volumes:
            - .:/srv
        ports:
            - '3000:3000'
        links:
            - game_api_mysql
        environment:
            - VIRTUAL_PROTO=http
            - VIRTUAL_HOST=game-api.loc
            - VIRTUAL_PORT=3000
            - NODE_ENV=development
            - DB_HOST=game_api_mysql
            - DB_USER=root
            - DB_PASSWORD=
            - DB_NAME=game_api_development
            - DB_PORT=3310
            - GELF_HOSTNAME=127.0.0.1
            - GELF_PORT=12201
            - NEW_RELIC_LICENSE_KEY=

    game_api_mysql:
        image: mysql:5.7
        healthcheck:
            test: 'mysqladmin --no-beep ping'
        ports:
            - '3310:3306'
        environment:
            - MYSQL_DATABASE=game_api_development
            - MYSQL_ROOT_PASSWORD=
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes

networks:
    default:
        external:
            name: strikebit
